version: "3"

services:
  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
     --character-set-server=utf8mb4
     --collation-server=utf8mb4_general_ci
     --explicit_defaults_for_timestamp=true
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=seqanadb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      
    
    volumes:
      - ./data/table_schema.sql:/docker-entrypoint-initdb.d/schema.sql
      #- mysql_data:/var/lib/mysql/
    ports:
      - "3306:3306"
    restart: always

  python_seqana:
    image: python-test
    build: program
    command: sh -c "sleep 50s ; python ./environment.py"
    depends_on: 
      - mysqldb
    volumes:
      - ./data:/data
      
#volumes:      
  #mysql_data:
     #driver: local
      
      

